// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabsYurbGzpRmrmhEP2DdCFmAOA3ADJMg',
    appId: '1:916272372318:web:7c9efeae5f06652447b2cf',
    messagingSenderId: '916272372318',
    projectId: 'login-35e6a',
    authDomain: 'login-35e6a.firebaseapp.com',
    storageBucket: 'login-35e6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlieM756dYifmXy06YW3YJ-cNfI3Vykk',
    appId: '1:916272372318:android:08b7df4aab4fc5f347b2cf',
    messagingSenderId: '916272372318',
    projectId: 'login-35e6a',
    storageBucket: 'login-35e6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWKatR3v2pcysTuITfXP0tUXla3Fsl1Q',
    appId: '1:916272372318:ios:086ee646af18924747b2cf',
    messagingSenderId: '916272372318',
    projectId: 'login-35e6a',
    storageBucket: 'login-35e6a.appspot.com',
    iosClientId: '916272372318-9j35fkfulald876b5sqhutfu3uqaaos5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
